### PR TITLE
Fix: Compute the task list item index correctly.

### LINKED ISSUE #25: Anchor tag in the markup corrupts the position calculations.
### Steps to reproduce

- Modify the index.html file in the example folder as shown below:
```html
...
    <task-lists sortable>
      <ul class="contains-task-list">
        <a name="anchor" />    <!-- This is the change -->   
        <li class="task-list-item">
          <label>
            <input type="checkbox" class="task-list-item-checkbox" />
            Hubot
          </label>
        </li>
        <li class="task-list-item">
          <label>
            <input type="checkbox" class="task-list-item-checkbox" />
            Bender
          </label>
        </li>
      </ul>
    </task-lists>
...
```

- Check/uncheck the checkboxes on the top. The item position is reported as -1.

Screenshot 2021-07-29 at 10 45 11

### PR DESCRIPTION
**Pull request by chanakyabhardwajj**
Fixes #25 

### Problem
If a task list contained elements other than task list items (for example `<a>`) then the position of the checked/unchecke task list item was being calculated incorrectly.

### Fix
The position of a task list item should be computed using only other task list items (and ignoring any other elements).

### CODE REVIEW

File: src/task-lists-element.ts [hunk 1]
```diff
@@ -132,7 +132,11 @@ function position(checkbox: HTMLInputElement): [number, number] {
   const list = taskList(checkbox)
   if (!list) throw new Error('.contains-task-list not found')
   const item = checkbox.closest('.task-list-item')
-  const index = item ? Array.from(list.children).indexOf(item) : -1
+  const index = item
+    ? Array.from(list.children)
+        .filter(el => el.classList.contains('task-list-item'))
+        .indexOf(item)
+    : -1
```
Comment (koddsson) [inline src/task-lists-element.ts:139]: This has become really hard to read. What do you think about changing this to something like:

```suggestion
  const listItems = Array.from(list.children).filter(el => el.classList.contains('task-list-item'))
  const index = item ? listItems.indexOf(item) : -1
```

**Comment by chanakyabhardwajj** [comment]
@koddsson Could you please review again?

**Comment by koddsson** [comment]
Sorry, this wasn't showing up in the first responder queue because the reviewer's team wasn't requested. It is now, but I'll take this on.
